server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # Replace with your Eureka server address
    fetchRegistry: true
    registerWithEureka: false # Gateway typically doesn't need to register itself if it's only consuming services
  instance:
    preferIpAddress: true # Optional: prefer IP address over hostname for registration
spring:
  application:
      name: fountation-gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: fountation-user-service
          uri: lb://fountation-user-service # MY-SERVICE-ID is the application name of your microservice in Eureka
          predicates:
            - Path=/user/** # Define the path predicate for this route
          filters:
            - RemoveRequestHeader=favicon.ico
            - RemoveRequestHeader=default-ui.css
  security:
    oauth2:
      client:
        provider:
          spring:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            user-info-uri: http://localhost:9000/userinfo
            jwk-set-uri: http://localhost:9000/oauth2/jwks
        registration:
          internal-auth-server:
            authorization-grant-type: authorization_code
            client-id: "fountation-authorization-service-id"
            client-name: "API Gateway Client"
            client-secret: "{noop}fountation-authorization-service-secret"
            redirect-uri: 'http://localhost:9000/login/oauth2/code/{registrationId}'
            scope: openid, profile, accounts.read
            provider: spring
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
logging:
  level:
    org:
      springframework:
        security: debug
    org.springframework.security.web.server.util.matcher: INFO

